### ISSUE TITLE
Create more detailed testing docs for producing custom r-c-s builds

### ISSUE THREAD

**Issue by skhamis** [mozilla/rust-components-swift#28]
The firefox for iOS team ran into an issue using the local build section of r-c-s to produce a test build to import:

Steps to reproduce:
1. Have a fork/branch of r-c-s
2. Follow the instructions https://github.com/mozilla/rust-components-swift#testing-locally
3. Since there was no `--as-version` defined it'll use "main"
4. Check in and push the branch to consume it as a `https://www.github.com/....` in the SPM
 
Results: It will fail due to the Package.swift using the latest binary of a RELEASED version of application services rather than the main xcframework:
https://github.com/mozilla/rust-components-swift/blob/main/Package.swift#L5-L6

We should mention that whatever version of application services you use (main, release version, etc) you need to either update the package.swift lines above or use the EXACT same version otherwise the uniffi builds will fail (or other weird reasons).

**Comment by tarikeshaq** [comment]
There are a few docs in https://mozilla.github.io/application-services/book/howtos/locally-published-components-in-firefox-ios.html so I think it's safe to close this, @skhamis  feel free to reopen in application-services, I'm going to disable issues on this repo as they might easily get ignored (and one less place to see tickets!)
