### ISSUE TITLE
Remove glean as a dependency from rust-components-swift

### ISSUE THREAD

**Issue by skhamis** [mozilla/rust-components-swift#29]
The FxiOS team is having an issue with Glean being packaged as part of the SPM due to the nature of the their dependency graph. We tested with https://github.com/mozilla/rust-components-swift/pull/27 and @nbhasin2 confirmed that he was able to successfully deploy to a hardware device (where the current release caused cycle dependency issues).

We'll have to coordinate with the Focus team to ensure they're onboard with this and won't cause any forward issues (though it should be as simple as adding glean-swift as it's own SPM).

**Comment by skhamis** [comment]
@st3fan do you see any issues with this as having Glean added to the Focus project as its own SPM?

**Comment by skhamis** [comment]
This PR: https://github.com/mozilla/rust-components-swift/pull/27 along with all the changes @nbhasin2 doing on firefox-ios successfully building with SPM. However it'll require moving Glean out of r-c-s and the consumers (focus-ios and firefox-ios) will be responsible for updating Glean. 

Pinging relevant stakeholders if there is any issues: @st3fan, @badboy

**Comment by badboy** [comment]
That's conceptually fine for Glean. Also means we don't need release coordination with a-s anymore (I enjoy working with you, but it is nonetheless some overhead for us).

Where can I read the details about the "cycle dependency issues"? Both this issue and #27 are rather vague on details, I would like to understand what the underlying issue is.

**Comment by nbhasin2** [comment]
@badboy SPM is fairly new and has its quirks and limitation, one of them is adding nested dependencies would work for a simpler project but it doesn't for our Firefox iOS which has over 15+ targets that work together with each other. We can look into refactoring that to be more linear would require a tremendous amount of time and in the end, might not be too useful either. 

Long story short, adding an SPM package to multiple targets in one project results in an error that isn't easy to resolve unless a new XCode releases. The best way for us to do this is to divide the dependency and add it only where it's required. 

Let me know if this helps and happy to go further into details about SPM if you require.

**Comment by nbhasin2** [comment]
Having glean as separate dependency gives us the freedom to tweak the project accordingly and support Firefox iOS with multiple targets. For example

Target A requires -> Glean & A~S
Target B depends on -> some Target A files but only require A~S and not Glean

Here all we need to do is not link Glean to Target B but if everything is nested into one dependency then XCode SPM isn't smart enough to figure out that we only need one instance and it ends up adding two frameworks while doing an archive. This is a known issue and folks use custom scripts to get away from this which is not the best solution.

To avoid all this it's better to keep Glean / A~S separate.

**Comment by badboy** [comment]
As I said: I'm all for moving it out. That simplifies our release process again.

I'm still curious if you have some detailed log (locally or from CI) which shows a build failure with the old package.
I simply want to understand what we ran into, so we're not running into that again 6 months from now.

**Comment by badboy** [comment]
Where are we with this? I see firefox-ios `main` branch is now using rust-components-swift through @skhamis' fork and Glean directly.
What's the plan to get the changes back into the main branch here and when will we update Focus iOS to the same usage?

**Comment by skhamis** [comment]
@mozilla/glean Glean is officially moved outside of this repository. So anyone using glean will pull it in as a separate package. So that should be easier for Glean to update their relevant packages -- as for using my fork on ios, that was mainly to get the big merge in but they have since merged to use the offical a-s/r-c-s versions now. https://github.com/mozilla-mobile/firefox-ios/pull/9933

This task is essentially done so closing now!

**Comment by badboy** [comment]
Thanks!
